<?php

namespace Proxies;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Auth_Model_ArtisanProxy extends \Auth_Model_Artisan implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }
    
    
    public function hasActivite($id)
    {
        $this->__load();
        return parent::hasActivite($id);
    }

    public function hasZone($id)
    {
        $this->__load();
        return parent::hasZone($id);
    }

    public function hasDepartement($code)
    {
        $this->__load();
        return parent::hasDepartement($code);
    }

    public function addActivite(\Auth_Model_Activite $activite)
    {
        $this->__load();
        return parent::addActivite($activite);
    }

    public function addDepartement(\Auth_Model_Departement $departement)
    {
        $this->__load();
        return parent::addDepartement($departement);
    }

    public function removeDepartement(\Auth_Model_Departement $departement)
    {
        $this->__load();
        return parent::removeDepartement($departement);
    }

    public function __set($attr, $val)
    {
        $this->__load();
        return parent::__set($attr, $val);
    }

    public function __get($attr)
    {
        $this->__load();
        return parent::__get($attr);
    }

    public function toArray()
    {
        $this->__load();
        return parent::toArray();
    }

    public function getId_artisan()
    {
        $this->__load();
        return parent::getId_artisan();
    }

    public function getNom_artisan()
    {
        $this->__load();
        return parent::getNom_artisan();
    }

    public function getPrenom_artisan()
    {
        $this->__load();
        return parent::getPrenom_artisan();
    }

    public function getRaison_sociale()
    {
        $this->__load();
        return parent::getRaison_sociale();
    }

    public function getEmail_artisan()
    {
        $this->__load();
        return parent::getEmail_artisan();
    }

    public function getTelephone_fixe($formated = false)
    {
        $this->__load();
        return parent::getTelephone_fixe($formated);
    }

    public function getTelephone_portable($formated = false)
    {
        $this->__load();
        return parent::getTelephone_portable($formated);
    }

    public function getFax()
    {
        $this->__load();
        return parent::getFax();
    }

    public function getRcs()
    {
        $this->__load();
        return parent::getRcs();
    }

    public function getSiret()
    {
        $this->__load();
        return parent::getSiret();
    }

    public function getCode_NAF()
    {
        $this->__load();
        return parent::getCode_NAF();
    }

    public function getHoraireRDV()
    {
        $this->__load();
        return parent::getHoraireRDV();
    }

    public function getLogin()
    {
        $this->__load();
        return parent::getLogin();
    }

    public function getPass()
    {
        $this->__load();
        return parent::getPass();
    }

    public function getDescription()
    {
        $this->__load();
        return parent::getDescription();
    }

    public function getQualification()
    {
        $this->__load();
        return parent::getQualification();
    }

    public function getAdresse()
    {
        $this->__load();
        return parent::getAdresse();
    }

    public function getAdresse2()
    {
        $this->__load();
        return parent::getAdresse2();
    }

    public function getCode_postal()
    {
        $this->__load();
        return parent::getCode_postal();
    }

    public function getVille()
    {
        $this->__load();
        return parent::getVille();
    }

    public function getCredit_dispo()
    {
        $this->__load();
        return parent::getCredit_dispo();
    }

    public function getCenter()
    {
        $this->__load();
        return parent::getCenter();
    }

    public function getRayon()
    {
        $this->__load();
        return parent::getRayon();
    }

    public function getLat()
    {
        $this->__load();
        return parent::getLat();
    }

    public function getLng()
    {
        $this->__load();
        return parent::getLng();
    }

    public function getGeolocalisation()
    {
        $this->__load();
        return parent::getGeolocalisation();
    }

    public function setId_artisan($id_artisan)
    {
        $this->__load();
        return parent::setId_artisan($id_artisan);
    }

    public function setNom_artisan($nom_artisan)
    {
        $this->__load();
        return parent::setNom_artisan($nom_artisan);
    }

    public function setPrenom_artisan($prenom_artisan)
    {
        $this->__load();
        return parent::setPrenom_artisan($prenom_artisan);
    }

    public function setRaison_sociale($raison_sociale)
    {
        $this->__load();
        return parent::setRaison_sociale($raison_sociale);
    }

    public function setEmail_artisan($email_artisan)
    {
        $this->__load();
        return parent::setEmail_artisan($email_artisan);
    }

    public function setTelephone_fixe($telephone_fixe)
    {
        $this->__load();
        return parent::setTelephone_fixe($telephone_fixe);
    }

    public function setTelephone_portable($telephone_portable)
    {
        $this->__load();
        return parent::setTelephone_portable($telephone_portable);
    }

    public function setFax($fax)
    {
        $this->__load();
        return parent::setFax($fax);
    }

    public function setLogin($login)
    {
        $this->__load();
        return parent::setLogin($login);
    }

    public function setPass($pass)
    {
        $this->__load();
        return parent::setPass($pass);
    }

    public function setRcs($rcs)
    {
        $this->__load();
        return parent::setRcs($rcs);
    }

    public function setSiret($siret)
    {
        $this->__load();
        return parent::setSiret($siret);
    }

    public function setCode_NAF($code_NAF)
    {
        $this->__load();
        return parent::setCode_NAF($code_NAF);
    }

    public function setHoraireRDV($horaireRDV)
    {
        $this->__load();
        return parent::setHoraireRDV($horaireRDV);
    }

    public function setDescription($description)
    {
        $this->__load();
        return parent::setDescription($description);
    }

    public function setQualification($qualification)
    {
        $this->__load();
        return parent::setQualification($qualification);
    }

    public function setAdresse($adresse)
    {
        $this->__load();
        return parent::setAdresse($adresse);
    }

    public function setAdresse2($adresse2)
    {
        $this->__load();
        return parent::setAdresse2($adresse2);
    }

    public function setCode_postal($code_postal)
    {
        $this->__load();
        return parent::setCode_postal($code_postal);
    }

    public function setVille($ville)
    {
        $this->__load();
        return parent::setVille($ville);
    }

    public function setCredit_dispo($credit_dispo)
    {
        $this->__load();
        return parent::setCredit_dispo($credit_dispo);
    }

    public function setCenter($center)
    {
        $this->__load();
        return parent::setCenter($center);
    }

    public function setRayon($rayon)
    {
        $this->__load();
        return parent::setRayon($rayon);
    }

    public function setLat($lat)
    {
        $this->__load();
        return parent::setLat($lat);
    }

    public function setLng($lng)
    {
        $this->__load();
        return parent::setLng($lng);
    }

    public function setGeolocalisation($geolocalisation)
    {
        $this->__load();
        return parent::setGeolocalisation($geolocalisation);
    }

    public function getSpecialities()
    {
        $this->__load();
        return parent::getSpecialities();
    }

    public function getDepartements()
    {
        $this->__load();
        return parent::getDepartements();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id_artisan', 'nom_artisan', 'prenom_artisan', 'raison_sociale', 'email_artisan', 'telephone_fixe', 'telephone_portable', 'fax', 'rcs', 'siret', 'code_NAF', 'horaireRDV', 'description', 'pass', 'login', 'adresse', 'adresse2', 'code_postal', 'ville', 'credit_dispo', 'qualification', 'center', 'rayon', 'lat', 'lng', 'geolocalisation', 'activites', 'departements', 'zones', 'demandes');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields AS $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}