<div style="width: 650px; margin: 10px auto;">
	<div style="text-align: center; padding: 10px;"><img src="http://www.webonline2018.com/resources_fo_ehcg/img/company_logo_1.jpg" /></div>
	<h1 style="background-color:#0184c2;padding: 50px;color:#fff;text-align: center; font-size: 20px">Confirmation d'inscription</h1>
	<p>Bonjour <?= $this->artisan->nom_artisan ?> <?= $this->artisan->prenom_artisan ?>,</p>
	<p>Vous venez de vous inscrire sur notre site <a href="mister-devis.com">www.mister-devis.com</a> et nous sommes ravis de vous compter parmi nos partenaires.</p>
	<p>Voici vos identifiants de connexion à <strong>votre Espace Pro :</strong></p>
	
	<p>Identifiant : <strong><?= $this->artisan->login; ?></strong></p>
	<p>Mot de passe : <strong><?= $this->pass; ?></strong></p>
	
	<p><a href="http://pro.mister-devis.com">Espace Pro</a></p>
	
	<p>Prochainement un de nos conseillers vous contactera afin de préciser et complèter l'ensemble de vos informations.</p>
	<p>L'ensemble de l'équipe de <a href="http://www.mister-devis.com">www.mister-devis.com</a> vous remercie pour votre confiance</p>
	<p>Cordialement</p>
	
	<p style="margin-top: 50px">
		<strong>Georges KAPPLAN</strong><br><br>
		<span>
			Directeur Commercial<br> <a href="mailto:georges.kapplan@mister-devis.com">georges.kapplan@mister-devis.com</a><br> 09 88 77 27 00 </span>    <br><br>
		<img src="http://www.webonline2018.com/resources_fo_ehcg/img/company_logo_1.jpg" style="width: 80px" />
	</p>
</div>