<div style="width: 650px; margin: 10px auto;">
	<div style="text-align: center; padding: 10px;"><img src="http://www.webonline2018.com/resources_fo_ehcg/img/company_logo_1.jpg" /></div>
	<h1 style="background-color:#0184c2;padding: 50px;color:#fff;text-align: center; font-size: 20px">Notification d'inscription Artisan</h1>
	<p>Bonjour,</p>
	<p>Un nouveau artisan vient de s'inscrire sur le site <a href="mister-devis.com">www.mister-devis.com</a> .</p>
	<p>Voici ses identifiants de connexion à <strong>l'Espace Pro :</strong></p>
	
	<p>Identifiant : <strong><?= $this->login; ?></strong></p>
	<p>Mot de passe : <strong><?= $this->pass; ?></strong></p>
	<p>Cordialement</p>
</div>